### ISSUE TITLE
Possible breakage with current reply version

### ISSUE THREAD

**Issue by winks** [functional-koans/clojure-koan-engine#15]
Hi,
we have an open leiningen bug at https://github.com/technomancy/leiningen/issues/2326 and my investigation currently leads to a version conflict of koan-engine's and reply's jline version.

Maybe one of the koan-engine authors has an idea, I surely don't want to shift any blame here.

**Comment by trptcolin** [comment]
👍  fixed in 0.2.4 (there's no reason clojure-koan-engine should have this old jline dependency anymore).
